config/routes.rb
Rails.application.routes.draw do
  resources :map, only: [:index]

  resources :map_items

  resources :map_chips

end

app/models/map.rb
class Map < ActiveRecord::Base
  validates :x, :y,
    numericality: true,
    presence: true

  validates :x, uniqueness: { scope: :y }

  def self.append(*args)

    if args.length == 1 && args[0].kind_of?(Hash)
      self.create(args.first)
    else
      MapItem.create(
        x: args[0],
        y: args[1],
        map_chip: args[2]
      )
    end
  end

  class << self
    alias :add :append
    alias :new_item :new
  end
end

app/models/map_chip.rb
class MapChip < ActiveRecord::Base
end

app/models/map_item.rb
class MapItem < ActiveRecord::Base
  belongs_to :map_chip
  has_one :map
  has_one :position, as: :map, class_name: "Map"

  delegate :x, :x=,
           :y, :y=, to: :map, allow_nil: true

  def initialize(attributes = {}, options = {})
    super(attributes, options)
    self.map = Map.new(attributes.slice(:x, :y))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/map_chips_controller.rb
class MapChipsController < ApplicationController
  before_action :set_map_chip, only: [:show, :edit, :update, :destroy]

  # GET /map_chips
  # GET /map_chips.json
  def index
    @map_chips = MapChip.all
  end

  # GET /map_chips/1
  # GET /map_chips/1.json
  def show
  end

  # GET /map_chips/new
  def new
    @map_chip = MapChip.new
  end

  # GET /map_chips/1/edit
  def edit
  end

  # POST /map_chips
  # POST /map_chips.json
  def create
    @map_chip = MapChip.new(map_chip_params)

    respond_to do |format|
      if @map_chip.save
        format.html { redirect_to @map_chip, notice: 'Map chip was successfully created.' }
        format.json { render :show, status: :created, location: @map_chip }
      else
        format.html { render :new }
        format.json { render json: @map_chip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /map_chips/1
  # PATCH/PUT /map_chips/1.json
  def update
    respond_to do |format|
      if @map_chip.update(map_chip_params)
        format.html { redirect_to @map_chip, notice: 'Map chip was successfully updated.' }
        format.json { render :show, status: :ok, location: @map_chip }
      else
        format.html { render :edit }
        format.json { render json: @map_chip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /map_chips/1
  # DELETE /map_chips/1.json
  def destroy
    @map_chip.destroy
    respond_to do |format|
      format.html { redirect_to map_chips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map_chip
      @map_chip = MapChip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_chip_params
      params.require(:map_chip).permit(:name)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/controllers/map_items_controller.rb
class MapItemsController < ApplicationController
  before_action :set_map_item, only: [:show, :edit, :update, :destroy]

  # GET /map_items
  # GET /map_items.json
  def index
    @map_items = MapItem.all
  end

  # GET /map_items/1
  # GET /map_items/1.json
  def show
  end

  # GET /map_items/new
  def new
    @map_item = MapItem.new
    @map_item.map = Map.new
  end

  # GET /map_items/1/edit
  def edit
  end

  # POST /map_items
  # POST /map_items.json
  def create
    @map_item = MapItem.new(map_item_params)

    respond_to do |format|
      if @map_item.save
        format.html { redirect_to @map_item, notice: 'Map item was successfully created.' }
        format.json { render :show, status: :created, location: @map_item }
      else
        format.html { render :new }
        format.json { render json: @map_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /map_items/1
  # PATCH/PUT /map_items/1.json
  def update
    respond_to do |format|
      if @map_item.update(map_item_params)
        format.html { redirect_to @map_item, notice: 'Map item was successfully updated.' }
        format.json { render :show, status: :ok, location: @map_item }
      else
        format.html { render :edit }
        format.json { render json: @map_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /map_items/1
  # DELETE /map_items/1.json
  def destroy
    @map_item.destroy
    respond_to do |format|
      format.html { redirect_to map_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map_item
      @map_item = MapItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_item_params
      params.require(:map_item).permit(:map_chip_id, :x, :y)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MmoRpgTkr
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/map_chips/_form.html.haml
= form_for(@map_chip) do |f|
  - if @map_chip.errors.any?
    #error_explanation
      %h2
        = pluralize(@map_chip.errors.count, "error")
        prohibited this map_chip from being saved:
      %ul
        - @map_chip.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/map_chips/edit.html.haml
%h1 Editing map_chip
= render 'form'
= link_to 'Show', @map_chip
|
\#{link_to 'Back', map_chips_path}

app/views/map_chips/index.html.haml
%h1 Listing map_chips
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @map_chips.each do |map_chip|
      %tr
        %td= map_chip.name
        %td= link_to 'Show', map_chip
        %td= link_to 'Edit', edit_map_chip_path(map_chip)
        %td= link_to 'Destroy', map_chip, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Map chip', new_map_chip_path

app/views/map_chips/new.html.haml
%h1 New map_chip
= render 'form'
= link_to 'Back', map_chips_path

app/views/map_chips/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @map_chip.name
= link_to 'Edit', edit_map_chip_path(@map_chip)
|
\#{link_to 'Back', map_chips_path}

app/views/map_items/_form.html.haml
= form_for(@map_item) do |f|
  - if @map_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@map_item.errors.count, "error")
        prohibited this map_item from being saved:
      %ul
        - @map_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :x
    %br/
    = f.text_field :x
  .field
    = f.label :y
    %br/
    = f.text_field :y
  .field
    = f.label :map_chip_id
    %br/
    = f.collection_select :map_chip_id, MapChip.all, :id, :name

  .actions
    = f.submit

app/views/map_items/edit.html.haml
%h1 Editing map_item
= render 'form'
= link_to 'Show', @map_item
|
\#{link_to 'Back', map_items_path}

app/views/map_items/index.html.haml
%h1 Listing map_items
%table
  %thead
    %tr
      %th X
      %th Y
      %th Map chip
      %th{:colspan => "3"}
  %tbody
    - @map_items.each do |map_item|
      %tr
        %td= map_item.x
        %td= map_item.y
        %td= '"' +  map_item.map_chip.name + '"'
        %td= link_to 'Show', map_item
        %td= link_to 'Edit', edit_map_item_path(map_item)
        %td= link_to 'Destroy', map_item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Map item', new_map_item_path

app/views/map_items/new.html.haml
%h1 New map_item
= render 'form'
= link_to 'Back', map_items_path

app/views/map_items/show.html.haml
%p#notice= notice
%p
  %strong Map chip:
  = @map_item.map_chip
= link_to 'Edit', edit_map_item_path(@map_item)
|
\#{link_to 'Back', map_items_path}